#!/bin/bash
# OLTPBENCH_HOME should be empty or end with "/"
java -Xmx8G -cp `$OLTPBENCH_HOME./classpath.sh bin` -Dlog4j.configuration=$OLTPBENCH_HOME./log4j.properties com.oltpbenchmark.DBWorkload $@
